apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-n3ti
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-n3ti
    app.kubernetes.io/part-of: tkrw-pr712-0075-0052-app
  name: devfile-sample-n3ti
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-n3ti
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-n3ti
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0052-tenant/tkrw-pr712-0075-0052-app/devfile-sample-n3ti@sha256:fe6c7ec7f2637f4ca6f90eb43a7ae175927bf034da28c568fa43a47b3f1327e7
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
